name: Keystone CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate personas (schema)
        shell: bash
        run: |
          set -e
          for f in personas/*.yaml; do
            python code/validate_asset.py "$f"
          done

      - name: Build seeds
        run: python code/seed_packager.py

      - name: Upload seeds as artifact
        uses: actions/upload-artifact@v4
        with:
          name: seeds
          path: seeds/*.json
